services:
#    calc_api.example:
#        class: Calc\ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    calc_api.references:
            class: Calc\ApiBundle\Controller\References