calc_web_homepage:
    path:     /
    defaults: { _controller: CalcCalcBundle:Web:index }
    methods: [GET]

calc_web_adminpage:
    path:     /admin
    defaults: { _controller: CalcCalcBundle:Admin:index }
    methods: [GET]

calc_web_admin_elements:
    path:     /admin/elements
    defaults: { _controller: CalcCalcBundle:Admin:elements }
    methods: [GET]

calc_web_admin_references:
    path:     /admin/references
    defaults: { _controller: CalcCalcBundle:Admin:references }
    methods: [GET]

calc_web_admin_configurations:
    path:     /admin/configurations
    defaults: { _controller: CalcCalcBundle:Admin:configurations }
    methods: [GET]

calc_admin_change_elements:
    path:     /admin/elements
    defaults: { _controller: CalcCalcBundle:Elements:update }
    methods: [POST]

calc_admin_change_configurations:
    path:     /admin/configurations
    defaults: { _controller: CalcCalcBundle:Configurations:update }
    methods: [POST]

calc_admin_change_references:
    path:     /admin/references
    defaults: { _controller: CalcCalcBundle:References:update }
    methods: [POST]

calc_web_templates:
    path:     /templates
    defaults: { _controller: CalcCalcBundle:Web:templates }
    methods: [GET]

calc_api_references:
    path:     /references
    defaults: { _controller: CalcCalcBundle:References:list }
    methods: [GET]

calc_api_elements:
    path:     /elements
    defaults: { _controller: CalcCalcBundle:Elements:list }
    methods: [GET]

calc_api_configurations:
    path:     /configurations
    defaults: { _controller: CalcCalcBundle:Configurations:list }
    methods: [GET]
