calc_web_homepage:
    path:     /
    defaults: { _controller: CalcCalcBundle:Web:index }
    methods: [GET]

calc_web_adminpage:
    path:     /admin
    defaults: { _controller: CalcCalcBundle:Admin:index }
    methods: [GET]

calc_web_admin_elements:
    path:     /admin/elements
    defaults: { _controller: CalcCalcBundle:Admin:elements }
    methods: [GET]

calc_admin_change_elements:
    path:     /admin/elements
    defaults: { _controller: CalcCalcBundle:Elements:update }
    methods: [POST]

calc_web_templates:
    path:     /templates
    defaults: { _controller: CalcCalcBundle:Web:templates }
    methods: [GET]

calc_api_references:
    path:     /references
    defaults: { _controller: CalcCalcBundle:References:list }
    methods: [GET]

calc_api_elements:
    path:     /elements
    defaults: { _controller: CalcCalcBundle:Elements:list }
    methods: [GET]

calc_api_reference:
    path:     /references/{name}
    defaults: { _controller: CalcCalcBundle:References:show }
    methods: [GET]

calc_api_reference_add:
    path:     /references
    defaults: { _controller: CalcCalcBundle:References:add }
    methods: [POST]

calc_api_reference_delete:
    path:     /references/{id}
    defaults: { _controller: CalcCalcBundle:References:delete }
    methods: [DELETE]

calc_api_reference_update:
    path:     /references/{name}/{id}
    defaults: { _controller: CalcCalcBundle:References:edit }
    methods: [PATCH]
